name: CI
on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            - name: npm install
              run: npm install --no-fund
            - name: Unit tests
              run: npm run test
              env:
                  test_authToken: ${{secrets.TEST_AUTHTOKEN}}
                  app_secret: ${{secrets.APP_SECRET}}
                  app_id: ${{secrets.APP_ID}}
            - name: Coverage
              run: npm run coverage
              env:
                  test_authToken: ${{secrets.TEST_AUTHTOKEN}}
                  app_secret: ${{secrets.APP_SECRET}}
                  app_id: ${{secrets.APP_ID}}
